### ISSUE TITLE
Email Prof. Brainard to confirm group

### ISSUE THREAD

**Issue by will-rubin** [will-rubin/SoftwareEngineeringS24#1]
Email the following to brainark@newpaltz.edu 

Subject: Software Engineering Group Confirmation

Group members:
Alexander Wyant
Cyrus Mika
William Rubin

**Comment by alexwyant** [comment]
I sent the email and everything looks good so far. Did you set up all of part 1 so far?

**Comment by alexwyant** [comment]
Sounds good. Just leave a comment on what you want us to do. Thanks for the work so far.

**Comment by will-rubin** [comment]
Yo, you want to meet up with Cyrus and I around 12 tomorrow to finish this
part up? I think it would be way easier

**Comment by alexwyant** [comment]
That works. I have a class at 12:30 so I wouldn't be able to meet for long. Let me know the details. My number is 845-392-3742. That would be easier to get in touch.
